### ISSUE TITLE
Fix Error: Failed to get an answer from all nodes

### ISSUE THREAD

**Issue by dominic22** [iotaledger/integration-services#122]
- fix problem
- add migration script

Happens on publish signed doc and also when adding data to a streams channel

error : Error from streams sdk: Failed to get an answer from all nodes
[LOGGER]  [2021-09-24 15:39:49]  error : Error: could not add logs to the channel
    at StreamsService.<anonymous> (/Users/dominiczettl/repositories/ensuresec/e-commerce-audit-log/api/src/services/streams-service.ts:92:10)
    at step (/Users/dominiczettl/repositories/ensuresec/e-commerce-audit-log/api/src/services/streams-service.ts:52:23)
    at Object.throw (/Users/dominiczettl/repositories/ensuresec/e-commerce-audit-log/api/src/services/streams-service.ts:33:53)
    at rejected (/Users/dominiczettl/repositories/ensuresec/e-commerce-audit-log/api/src/services/streams-service.ts:25:65)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[LOGGER]  [2021-09-24 15:39:49]  error : could not add the logs

**Comment by mastrogiovanni** [comment]
Maybe we need to capture this error and understand how to handle/return it on client side

**Comment by dominic22** [comment]
Following will be tackled and improved to avoid problems which could happen according to this error:

Currently the serverIdentity Document will be stored in the db and always updated when it is for instance revoking a subscription. This could lead to inconsistency against the tangle. Hence this should be removed and only the keys + latest hash should be stored there.

=> Also consider if we even store the hash or do always request the latest hash from the tangle.
