### ISSUE TITLE
Error while npm run setup-api in ssi-bridge

### ISSUE THREAD

**Issue by sandevins** [iotaledger/integration-services#577]
Hi,

I followed this tutorial: https://wiki.iota.org/integration-services/getting_started/installation/node_setup

And when running the `npm run setup-api` in the ssi-bridge part, this error occurs.

```
> ssi-bridge@0.1.4 setup-api /home/myuser/integration-services/api/ssi-bridge
> npm-run-all build start-setup-api


> ssi-bridge@0.1.4 build /home/myuser/integration-services/api/ssi-bridge
> npm-run-all build-tsc build-lint


> ssi-bridge@0.1.4 build-tsc /home/myuser/integration-services/api/ssi-bridge
> tsc --project ./


> ssi-bridge@0.1.4 build-lint /home/myuser/integration-services/api/ssi-bridge
> eslint src --ext .js,.jsx,.ts,.tsx

=============

WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.

You may find that it works just fine, or you may not.

SUPPORTED TYPESCRIPT VERSIONS: >=3.3.1 <4.5.0

YOUR TYPESCRIPT VERSION: 4.6.4

Please only submit bug reports when using the officially supported version.

=============

> ssi-bridge@0.1.4 start-setup-api /home/myuser/integration-services/api/ssi-bridge
> node dist/index.js setup-api

/home/myuser/integration-services/api/ssi-bridge/node_modules/@iota/is-shared-modules/node_modules/@sinclair/typebox/typebox.js:86
    schemas;
           ^

SyntaxError: Unexpected token ;
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/myuser/integration-services/api/ssi-bridge/node_modules/@iota/is-shared-modules/lib/models/schemas/user-types.js:4:19)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ssi-bridge@0.1.4 start-setup-api: `node dist/index.js setup-api`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ssi-bridge@0.1.4 start-setup-api script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/myuser/.npm/_logs/2022-06-10T10_51_55_947Z-debug.log
ERROR: "start-setup-api" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ssi-bridge@0.1.4 setup-api: `npm-run-all build start-setup-api`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ssi-bridge@0.1.4 setup-api script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/myuser/.npm/_logs/2022-06-10T10_51_55_970Z-debug.log
```

Any idea of the cause? I'm not too proficient with node.js.

**Comment by sandevins** [comment]
I found that the error was the node version. I missed that requirment.
